import AppFamilyLocalizationQA
import Foundation

enum HibiLensLocalizationQAConfiguration {
    static let expectedLocalizableKeys: Set<String> = [
        "accessibility.back",
        "accessibility.playPronunciation",
        "capture.camera.cannotCaptureNow",
        "capture.camera.starting",
        "capture.cameraAccess.message",
        "capture.cameraAccess.title",
        "capture.cameraUnavailable.message",
        "capture.cameraUnavailable.title",
        "capture.error.title",
        "capture.newCard",
        "capture.photo.accessibility",
        "capture.photo.failed",
        "capture.photoImport.failed",
        "capture.save.failed",
        "common.cancel",
        "common.done",
        "common.save",
        "home.captureNow",
        "home.discovery.subtitle",
        "home.discovery.title",
        "home.emptyKeepsake",
        "home.keepsakes.title",
        "home.newKeepsake",
        "home.progress.title",
        "home.seeAll",
        "home.stat.thisMonth",
        "home.stat.today",
        "home.stat.wordsCaptured",
        "nav.capture",
        "nav.home",
        "nav.personal",
        "nav.review",
        "personal.appearance",
        "personal.appearance.dark",
        "personal.appearance.day",
        "personal.appearance.system",
        "personal.discoveries",
        "personal.gallery.title",
        "personal.information",
        "personal.mastered",
        "personal.privacyPolicy",
        "personal.sourcesAndLicenses",
        "personal.sourcesAndLicenses.apacheLicense",
        "personal.sourcesAndLicenses.body",
        "personal.sourcesAndLicenses.ccBySa",
        "personal.sourcesAndLicenses.edrdgLicense",
        "personal.sourcesAndLicenses.jmdictProject",
        "personal.sourcesAndLicenses.siglipModel",
        "personal.sourcesAndLicenses.siglipProject",
        "personal.support",
        "personal.terms",
        "personal.thisMonth",
        "personal.wordsCaptured",
        "placeholder.screenInProgress",
        "review.delete.accessibility.label",
        "review.delete.alert.title",
        "review.delete.confirm",
        "review.learning",
        "review.learning.empty.message",
        "review.learning.empty.title",
        "review.mastered",
        "review.mastered.empty.message",
        "review.mastered.empty.title",
        "subjectLift.cutoutCreationFailed",
        "subjectLift.imageEncodingFailed",
        "subjectLift.invalidImage",
        "subjectLift.noSubjectDetected",
        "subscription.product.free",
        "subscription.product.proMonthly",
        "subscription.product.proQuarterly",
        "subscription.product.proYearly",
    ]

    static let allowedProductionLiterals: Set<String> = [
        // Internal identifiers, storage paths, and extensions.
        "coordinateSpaceName",
        "vocabularyDetailTransitionRoot",
        "app.appearance.preference",
        "home",
        "capture",
        "review",
        "personal",
        "sources-and-licenses",
        "processed-images",
        "processed-images/",
        "processed-thumbnails",
        "processed-thumbnails/",
        "thumbnail",
        "full",
        "unknown",
        "JapCaptureStorage",
        "png",
        "object",
        "card_media.assets.generate",

        // SF Symbols.
        "photo.on.rectangle.angled",
        "calendar.badge.clock",
        "sparkles",
        "house",
        "camera",
        "menucard",
        "person",
        "circle.lefthalf.filled",
        "envelope",
        "shield.lefthalf.filled",
        "doc.text",
        "text.document",
        "chevron.left",
        "waveform",
        "xmark",
        "ellipsis",
        "chevron.right",
        "chevron.up.chevron.down",
        "arrow.up.right",
        "link",
        "plus",

        // Model and resource names.
        "SigLIPImageLabelClassifier",
        "siglip_base_patch16_224_image",
        "siglip-object-vocabulary-text-embeddings",
        "object-vocabulary",
        "pixel_values",
        "image_embeds",
        "var_0",
        "mlmodelc",
        "json",
        "USD",

        // Locale and language identifiers.
        "zh",
        "ja-JP",

        // Stable persisted subscription seed values; presentation uses localizedDisplayName.
        "Free",
        "Pro Monthly",
        "Pro Quarterly",
        "Pro Yearly",

        // Home empty-state samples intentionally remain learning content under the approved localization boundary.
        "CAT",
        "Neko",
        "Cat",
        "WATER",
        "Mizu",
        "Water",
        "cup.and.saucer.fill",
        "koppu",
        "CUP",
        "book.closed.fill",
        "hon",
        "BOOK",

        // Logging, telemetry, and developer-facing diagnostics.
        "(none)",
        "JAPCAPTURE_PERFORMANCE_LOGGING",
        "com.example.HibiLens.camera-session",
        "com.example.HibiLens",
        "Camera",
        "auth=granted",
        "auth=denied",
        "auth=unknown",
        "configuring",
        "config-failed",
        "already-running",
        "No back camera device available",
        "Failed to create AVCaptureDeviceInput",
        "Session cannot add camera input",
        "Session cannot add photo output",
        "motion=unavailable",
        "motion=started",
        "Session interruption ended",
        "interruption-ended",
        "authorized",
        "notDetermined",
        "denied",
        "restricted",
        "portrait",
        "portraitUpsideDown",
        "landscapeLeft",
        "landscapeRight",
        "faceUp",
        "faceDown",
        "unknownDefault",
        "SigLIP text embedding dimension must be greater than zero.",
        "SigLIP text embedding labels cannot be empty.",
        "The image could not be prepared for SigLIP.",
        "The SigLIP Core ML model did not return an image embedding output.",
        "The SigLIP Core ML model returned an empty image embedding.",
        "The SigLIP Core ML model does not declare a pixel_values input.",
        #"Failed to create SwiftData container: \(error)"#,
        #"review.page.appear.\(tab.title.lowercased())"#,
        "[ContentView] presentCapture",
        #"[SigLIPImageLabelClassifier] app_prewarm=(error) \(error.localizedDescription)"#,
        #"[\(imageLabelClassifier.displayName)] prewarm=(error) \(error.localizedDescription)"#,
        #"[\(imageLabelClassifier.displayName)] labels=(error) \(error.localizedDescription)"#,
        #"stored_image.cache_hit.\(performanceLabel(for: relativePath))"#,
        #"stored_image.load.\(performanceLabel(for: relativePath))"#,
        #"[Performance] \(name)"#,
        #"[Performance] \(name)=\(String(format: "%.2f", elapsedMilliseconds))ms"#,
        #"Missing bundled SigLIP text embedding resource: \(name).json"#,
        #"SigLIP text embedding labels cannot include leading or trailing whitespace: \(label)."#,
        #"Duplicate SigLIP text embedding label: \(label)."#,
        #"SigLIP text embedding dimension mismatch for label: \(label)."#,
        #"Missing bundled SigLIP image model: \(modelName).mlmodelc"#,
        #"The SigLIP Core ML model declares an unsupported pixel_values input type: \(inputType)."#,
        #"Vocabulary resource '\(resourceName).json' is missing from the app bundle."#,
        #"[\(backendName)] labels=\(labelText)"#,
        #"auth=\(authorization.debugName)"#,
        #"running inputs=\(self.session.inputs.count) outputs=\(self.session.outputs.count)"#,
        #"Using camera device: \(device.localizedName, privacy: .public)"#,
        #"card-rotation motion=\(motionAngle.debugDescription) device=\(deviceOrientation.debugName) angle=\(resolvedAngle.debugDescription)"#,
        #"card-orientation device=\(lastUsableDeviceOrientation.debugName)"#,
        #"Runtime error: \(String(describing: error), privacy: .public)"#,
        #"runtime-error=\(error?.code.rawValue ?? -1)"#,
        #"Session interrupted: \(reasonRawValue)"#,
        #"interrupted=\(reasonRawValue)"#,
        #"[CameraService] \(message)"#,
        #"processed-images/\(UUID().uuidString).\(sanitizedExtension)"#,
        #"processed-thumbnails/\(UUID().uuidString).\(sanitizedExtension)"#,

        // External destinations and license references.
        "mailto:klproductgethelp@gmail.com",
        "https://kiethrios.github.io/PrivacyPolicy/",
        "HibiLensSupport_en.html",
        "HibiLensSupport_zh-Hans.html",
        "HibiLensPrivacyPolicy_en.html",
        "HibiLensPrivacyPolicy_zh-Hans.html",
        "HibiLensTerms_en.html",
        "HibiLensTerms_zh-Hans.html",
        "https://www.edrdg.org/edrdg/licence.html",
        "https://www.edrdg.org/wiki/index.php/JMdict-EDICT_Dictionary_Project",
        "https://creativecommons.org/licenses/by-sa/4.0/",
        "https://huggingface.co/google/siglip-base-patch16-224",
        "https://github.com/google-research/big_vision",
        "https://www.apache.org/licenses/LICENSE-2.0"
    ]

    static let catalog = LocalizationCatalogConfiguration(
        expectedSourceLanguage: "en",
        requiredLanguages: ["en", "zh-Hans"],
        expectedTranslatedKeys: expectedLocalizableKeys
    )

    static func sourceTree(projectRoot: URL) -> SwiftSourceTreeAuditConfiguration {
        SwiftSourceTreeAuditConfiguration(
            sourceRoot: projectRoot.appendingPathComponent("JapCapture"),
            excludedPathSubstrings: [
                "/Views/DesignPreview/",
                "/App/PreviewModelContainer.swift",
                "/Localization/AppL10n.swift"
            ],
            literalConfiguration: SwiftLiteralAuditConfiguration(
                allowedLiterals: allowedProductionLiterals
            )
        )
    }
}
